# Generated by Django 3.2 on 2021-04-16 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=30)),
                ('last', models.CharField(max_length=30)),
                ('short', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=40)),
                ('contact', models.CharField(max_length=10)),
                ('contact_ext', models.CharField(max_length=5)),
                ('join_date', models.DateField()),
                ('large', models.CharField(max_length=300)),
                ('medium', models.CharField(max_length=300)),
                ('thumbnail', models.CharField(max_length=300)),
                ('team', models.CharField(max_length=30)),
                ('job_title', models.CharField(max_length=30)),
                ('last_login', models.CharField(max_length=30)),
                ('loggedIn', models.CharField(max_length=30)),
            ],
        ),
    ]
