# Generated by Django 3.2 on 2021-04-16 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='join_date',
            field=models.CharField(max_length=30),
        ),
    ]
