# Generated by Django 3.2 on 2021-04-16 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_employee_join_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='viewers',
            field=models.IntegerField(blank=True, max_length=1000000, null=True),
        ),
    ]
